### ISSUE TITLE
Support for usernames and sessions

### ISSUE THREAD

**Issue by machitgarha** [philj56/greetd-mini-wl-greeter#1]
What's your opinion on adding support for entering username and selecting the session? I was thought of using tofi to present a menu, but it doesn't fit, it takes time and it's ugly to do so.

BTW, I love the simplicity spirit in two of your projects I've seen. Seriously.

**Comment by machitgarha** [comment]
You might ask, why I chose this tool in the first place (the name isn't short as tofi, so I can't call it). I loved the way tofi configuration worked. Simple, consistent, feature-full, and performant. And I've addicted to that simple type of configurations. :)

**Comment by philj56** [comment]
Hey, thanks for the kind words and sorry for the slow response! I probably won't add these as I don't really ever use them myself - I'd just switch the a different VT, or use a more full featured greeter if I needed them.
