### ISSUE TITLE
Error: Failed to load sharder shaders/vert.vert: No such file or directory

### ISSUE THREAD

**Issue by machitgarha** [philj56/greetd-mini-wl-greeter#2]
When building from source, shaders aren't visible to greetd-mini-wl-greeter, so executing it from anywhere other than the directory including the shaders leads to a crash with the following error:

```
[ERROR]: Failed to load shader shaders/vert.vert: No such file or directory.
```

This is surely unintended behavior, as the AUR installation works perfectly (used Toolbox to test).

**Comment by machitgarha** [comment]
Installing it again (using `ninja -C build install`) fixes the problem for a logged in session (temporarily).

**Comment by machitgarha** [comment]
So I read the PKGBUILD of the AUR package, and changed the build type to release, and everything is now working perfectly. I don't know if in debug build type this is intended behavior or not.

**Comment by philj56** [comment]
It was intended in debug, so I could quickly try things out in the vertex shader while developing as I didn't really expect anyone else to use this! But good catch
