### ISSUE TITLE
greeter doesnt fullscreen itself with cage 0.2.0

### ISSUE THREAD

**Issue by einetuer** [philj56/greetd-mini-wl-greeter#4]
when running greetd-mini-wl-greeter inside of cage 0.2.0 the app doesnt seem to go into fullscreen (it gets awkwardly stuck in the upper left corner). other apps seem to work fine though

i feel like this could be related to cage updating wlroots from 0.17 to 0.18?

**Comment by philj56** [comment]
Sorry for the slow response to this - it should be fixed in the latest commit. Thanks for the report!
